version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
      timezone: 'America/Chicago' # 12am Central Time
    commit-message:
      prefix: '[DEPENDABOT]'
    labels:
      - 'dependencies'
      - 'dependabot'
    open-pull-requests-limit: 8
    reviewers:
      - 'stefcameron'
    versioning-strategy: 'increase'
    ignore:
      - dependency-name: 'electron' # must be upgraded in lock-step with what Lens uses
      - dependency-name: 'node-fetch'
        versions: ['3.x'] # it's ESM-only, needs node:http/s modules that Lens/Electron 5.3.0 does not support
