name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    name: Lint > Format Check > Test > Build
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [lts/gallium] # @k8slens/core@^6.4.0 requires 16.x (2023/03/02)
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # TODO: this does work (it'll find the cache) but it appears it's not putting the cache
      #  back into ./node_modules because skipping the install step results in subsequent
      #  steps failing with messages like `prettier not found`, which implies there's no
      #  node_modules directory there with Prettier installed in it...
      #
      # - name: NPM cache check
      #   uses: actions/cache@v3
      #   id: npm-cache
      #   with:
      #     path: ${{ steps.setup.outputs.npm-cache-dir }}
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: Install dependencies
        # if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run fmt:check

      - name: Test
        run: npm run test:unit # TODO[PRODX-24209] change to test:coverage (and also in package.json 'test' script)

      - name: Build
        run: npm run build
